Feat/theming
celo-org/use-contractkit pull request #198
Opened 2022-05-19 17:07 UTC by nicolasbrugneaux

This is a big one that needs some discussing. We may want to take a different approach. I tried to stay backwards compatible with the dark and light theme. But this can easily be dropped in favour of providing themes during app's setup (or via `updateTheme`).

This addresses #145

2022-05-19 17:24 UTC, aaronmgdr commented on packages/example/components/theme-buttons.tsx
> +    <div
Please Make this a `<button>` for accessibility

2022-05-19 17:25 UTC, aaronmgdr commented on packages/example/components/theme-buttons.tsx
> +      </div>
This is pretty cool

2022-05-19 17:52 UTC, aaronmgdr requested changes
mostly just questions but There was one button that should be an `a`

2022-05-19 17:52 UTC, aaronmgdr commented on packages/react-celo/src/components/button.tsx
> +
Ive never seen the `as = 'element'`, `Component = as` before.

2022-05-19 17:52 UTC, aaronmgdr commented on packages/react-celo/src/screens/metamask.tsx
> +      <Button
missing `as =  'a'`

2022-05-19 17:52 UTC, aaronmgdr commented on packages/react-celo/src/components/button.tsx
> +  as = 'button',
id like to make this case that this should be required so we dont accidentally make buttons when anchor tags are the semantically correct thing to do

2022-05-19 17:52 UTC, aaronmgdr commented on packages/react-celo/src/utils/useTheme.ts
> +  console.log(theme);
remove

2022-05-19 20:06 UTC, nicolasbrugneaux commented on packages/example/pages/index.tsx
> +}
maybe? it's in the example app I didn't quite look for optimization there

2022-05-19 20:07 UTC, nicolasbrugneaux commented on packages/react-celo/src/utils/useTheme.ts
> +}
Note: That hook could be soooo much simpler if we didn't handle the html or body dark or tw-dark classnames.

2022-05-20 16:29 UTC, aaronmgdr commented on packages/react-celo/__tests__/react-celo-provider.tsx
> +      expect(result.current.network).toEqual(Mainnet);
I think this line can be remove right? copied from another test?

2022-05-20 16:30 UTC, aaronmgdr approved these changes

2022-05-22 12:28 UTC, merged