feat: add wallet-walletconnect to monorepo
celo-org/use-contractkit pull request #77
Opened 2021-12-03 00:33 UTC by Bijan-Massoumi

2021-12-14 14:28 UTC, nicolasbrugneaux approved these changes

2021-12-14 14:28 UTC, nicolasbrugneaux commented
LGTM

2021-12-14 14:35 UTC, nicolasbrugneaux requested changes
Looks good except the version for packages should be 2.0.1-dev AFAIK

2021-12-14 15:47 UTC, dckesler commented
Yeah we want all the packages in the use-contractkit monorepo to have the same version number

2021-12-20 17:24 UTC, dckesler approved these changes

2021-12-20 17:38 UTC, nicolasbrugneaux approved these changes

2021-12-20 20:12 UTC, merged